name: Build APK

on:
  workflow_dispatch:   # run manually
  push:
    branches:
      - main           # run automatically on push to main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            python3-setuptools \
            python3-dev \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            zlib1g-dev \
            libjpeg-dev \
            libfreetype6-dev \
            liblcms2-dev \
            pkg-config \
            autoconf \
            automake \
            libtool \
            cmake
          pip install --upgrade pip
          pip install buildozer cython==0.29.36

      - name: Build APK (with AIDL fix)
        run: |
          # Set Android SDK root
          export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
          # Add build-tools + platform-tools to PATH
          export PATH=$ANDROID_SDK_ROOT/build-tools/34.0.0:$ANDROID_SDK_ROOT/platform-tools:$PATH
          # Now run Buildozer
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: singboxconfig-apk
          path: bin/*.apk
