name: Build and Release Universal APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git zip unzip openjdk-17-jdk python3-pip python3-setuptools python3-dev libffi-dev libssl-dev libsqlite3-dev zlib1g-dev libjpeg-dev libfreetype6-dev liblcms2-dev pkg-config autoconf automake libtool cmake
        pip install --upgrade pip
        pip install cython==0.29.36

    - name: Read version from buildozer.spec
      id: get_version
      run: |
        VERSION=$(grep '^version =' buildozer.spec | cut -d'=' -f2 | tr -d ' ')
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Build APK
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        workdir: .
        build_command: buildozer -v android debug
        python_version: '3.9'

    - name: Rename Universal APK
      run: |
        mkdir -p release-apks
        cp bin/*.apk release-apks/singboxconfig-${{ steps.get_version.outputs.version }}-universal.apk

    - name: Install GitHub CLI
      run: sudo apt-get install -y gh

    - name: Authenticate gh
      run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

    - name: Upload APK to GitHub Release
      run: |
        if gh release view v${{ steps.get_version.outputs.version }} &>/dev/null; then
          echo "Release exists, uploading APK..."
          gh release upload v${{ steps.get_version.outputs.version }} release-apks/*.apk --clobber
        else
          echo "Creating new release..."
          gh release create v${{ steps.get_version.outputs.version }} release-apks/*.apk --title "Sing-Box Configurator v${{ steps.get_version.outputs.version }}" --notes "Universal APK build (arm64-v8a + armeabi-v7a)"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
