name: Build Universal APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            python3 python3-pip python3-setuptools git zip unzip openjdk-17-jdk \
            libffi-dev libssl-dev libjpeg-dev zlib1g-dev \
            autoconf automake libtool pkg-config

      # Step 3: Install python-for-android
      - name: Install python-for-android
        run: |
          pip install --upgrade pip
          pip install python-for-android

      # Step 4: Setup Android SDK & NDK properly
      - name: Setup Android SDK & NDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          
          yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses
          yes | sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.2.9519653"

      # Step 5: Patch autotools (libffi fix)
      - name: Patch autotools
        run: |
          autoreconf --install --force || true

      # Step 6: Build Universal APK with p4a
      - name: Build APK
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          p4a apk \
            --private . \
            --package=org.singbox.generator \
            --name "SingBox Generator" \
            --version 0.1 \
            --bootstrap=sdl2 \
            --requirements=python3,kivy,kivymd \
            --arch=armeabi-v7a \
            --arch=arm64-v8a \
            --arch=x86 \
            --arch=x86_64 \
            --sdk_dir=$ANDROID_HOME \
            --ndk_dir=$ANDROID_HOME/ndk/25.2.9519653 \
            --android_api=33 \
            --output-filename singbox-universal.apk

      # Step 7: Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SingBox-Universal-APK
          path: singbox-universal.apk
