name: Build Android APK (SingBox Generator)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Android SDK/NDK
        uses: actions/cache@v4
        with:
          path: |
            ~/android-sdk
          key: android-sdk-${{ runner.os }}-33
          restore-keys: |
            android-sdk-${{ runner.os }}

      - name: Cache p4a & pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.local/share/python-for-android
            .p4a
          key: p4a-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            p4a-${{ runner.os }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip wget curl build-essential \
            libncurses5 libstdc++6 python3 python3-pip \
            openjdk-17-jdk zlib1g zlib1g-dev \
            libffi-dev libssl-dev autoconf automake libtool

      - name: Install p4a
        run: |
          pip install --upgrade pip setuptools wheel
          pip install git+https://github.com/kivy/python-for-android.git

      - name: Setup Android SDK & NDK
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          mkdir -p $ANDROID_HOME/cmdline-tools
          if [ ! -d "$ANDROID_HOME/cmdline-tools/latest" ]; then
            wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
            unzip -q cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
            mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          fi
          yes | sdkmanager --licenses || true
          sdkmanager "platforms;android-33" "platform-tools" "build-tools;33.0.2" "ndk;25.2.9519653"

      - name: Build APK
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          p4a apk \
            --private . \
            --package=org.singbox.generator \
            --name "SingBox Generator" \
            --version 0.1 \
            --bootstrap=sdl2 \
            --requirements=python3,kivy,kivymd \
            --arch=armeabi-v7a \
            --arch=arm64-v8a \
            --arch=x86 \
            --arch=x86_64 \
            --sdk_dir=$ANDROID_HOME \
            --ndk_dir=$ANDROID_HOME/ndk/25.2.9519653 \
            --android_api=33 \
            --use-setup-py \
            --recipes=libffi,openssl,sqlite3 \
            --output-filename singbox-universal.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: singbox-universal
          path: singbox-universal.apk
