name: Build Unsigned APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            python3-pip python3-setuptools python3-wheel \
            python3-dev git zip unzip zlib1g-dev openjdk-17-jdk wget libncurses5

      # Step 3: Setup Android SDK + NDK
      - name: Setup Android SDK
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          mkdir -p $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O sdk.zip
          unzip sdk.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-33" "build-tools;33.0.2" "cmdline-tools;latest" "ndk;25.2.9519653"

      # Step 4: Install Buildozer
      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install cython buildozer

      # Step 5: Ensure buildozer.spec exists
      - name: Ensure buildozer.spec exists
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      # Step 6: Build unsigned APK
      - name: Build unsigned APK
        env:
          ANDROIDSDK: $HOME/android-sdk
          ANDROIDNDK: $HOME/android-sdk/ndk/25.2.9519653
          ANDROIDAPI: 33
          ANDROIDNDKVER: 25b
        run: |
          export PATH=$ANDROIDSDK/cmdline-tools/latest/bin:$ANDROIDSDK/platform-tools:$PATH
          buildozer -v android debug

      # Step 7: Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SingBoxGenerator-unsigned-apk
          path: bin/*.apk
