name: Build and Release APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

env:
  VERSION: 1.0.0  # Hardcoded app version

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ Set up Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    # 3️⃣ Install system dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git zip unzip openjdk-17-jdk python3-pip python3-setuptools python3-dev libffi-dev libssl-dev libsqlite3-dev zlib1g-dev libjpeg-dev libfreetype6-dev liblcms2-dev pkg-config autoconf automake libtool cmake
        pip install --upgrade pip
        # --- FIX: Removed pinned Cython version to ensure compatibility ---
        pip install cython

    # 4️⃣ Build APK (universal)
    - name: Build APK
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        workdir: .
        build_command: buildozer -v android debug
        python_version: '3.9'

    # 5️⃣ Install GitHub CLI
    - name: Install GitHub CLI
      run: sudo apt-get install -y gh

    # 6️⃣ Authenticate GitHub CLI
    - name: Authenticate gh
      run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

    # 7️⃣ Upload APK to GitHub Release
    - name: Upload APK to GitHub Release
      run: |
        # --- FIX: Use a wildcard to find the generated APK regardless of its exact name ---
        APK_FILE=$(find bin -name "*.apk" | head -n 1)
        if [ -z "$APK_FILE" ]; then
          echo "APK file not found!"
          exit 1
        fi
        
        if gh release view v${VERSION} &>/dev/null; then
          echo "Release exists, uploading APK..."
          gh release upload v${VERSION} "$APK_FILE" --clobber
        else
          echo "Creating new release..."
          gh release create v${VERSION} "$APK_FILE" --title "Sing-Box Configurator v${VERSION}" --notes "Universal APK build."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
