name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # 3. Install Buildozer
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            python3-setuptools \
            python3-dev \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            zlib1g-dev \
            libjpeg-dev \
            libfreetype6-dev \
            liblcms2-dev \
            pkg-config \
            autoconf \
            automake \
            libtool \
            cmake
          pip install --upgrade pip
          pip install buildozer cython==0.29.36

      # 4. Build APK
      - name: Build with Buildozer
        run: buildozer -v android debug

      # 5. Upload Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: singboxconfig-apk
          path: bin/*.apk
