name: Build and Release APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Build APK with Buildozer
      - name: Build APK
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          workdir: .
          command: android debug
          buildozer_version: "1.4.1"

      # 3. Read version from buildozer.spec
      - name: Get version from buildozer.spec
        id: get_version
        run: |
          version=$(grep '^version =' buildozer.spec | awk -F= '{print $2}' | tr -d ' ')
          echo "VERSION=$version" >> $GITHUB_ENV

      # 4. Create or update GitHub Release and upload APK
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          name: Sing-Box Configurator v${{ env.VERSION }}
          files: bin/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
