name: Build Universal APK with Python-for-Android

# This workflow runs on pushes to the 'main' branch or can be triggered manually.
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-android-p4a:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java (for Android SDK)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

      - name: Install Python dependencies (p4a, Cython)
        run: |
          pip install --upgrade cython
          pip install --upgrade python-for-android

      - name: Build universal unsigned APK with p4a
        run: |
          p4a apk \
            --universal \
            --unsigned \
            --requirements=python3,kivy,requests,pyyaml \
            --private=. \
            --package=com.yourdomain.singboxconfig \
            --name="Sing-box Config Maker" \
            --version=1.0 \
            --bootstrap=sdl2 \
            --permission=INTERNET \
            --permission=WRITE_EXTERNAL_STORAGE \
            --permission=READ_EXTERNAL_STORAGE \
            --entrypoint=TheBest_fixed_plus4.py \
            --android-api=33 \
            --ndk-version=25b \
            --release \
            --dist-name=singbox_dist

      - name: Find and rename APK
        run: |
          # The output file name is dynamic, so we find it and give it a static name.
          find dist -name "*-release-unsigned.apk" -exec mv {} singbox-config-maker-universal.apk \;

      - name: Upload Unsigned APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: singbox-config-maker-universal-apk
          path: singbox-config-maker-universal.apk
