name: Build APK (p4a)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            python3 python3-pip python3-setuptools git zip unzip openjdk-17-jdk \
            libffi-dev libssl-dev libjpeg-dev zlib1g-dev

      # Step 3: Install python-for-android (p4a)
      - name: Install python-for-android
        run: |
          pip install --upgrade pip
          pip install python-for-android cython

      # Step 4: Build APK with p4a
      - name: Build APK
        run: |
          p4a apk \
            --private . \
            --package=org.singbox.generator \
            --name "SingBox Generator" \
            --version 0.1 \
            --bootstrap sdl2 \
            --requirements=python3,kivy,kivymd,requests \
            --sdk-dir $HOME/android-sdk \
            --ndk-dir $HOME/android-ndk \
            --arch armeabi-v7a

      # Step 5: Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SingBoxGenerator-unsigned
          path: dist/*.apk
